<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <xacro:include filename="inertial_macros.xacro" />

    <xacro:property name="chassis_length" value="0.4"/>

    <xacro:property name="wheel_thickness" value="0.01"/>
    <xacro:property name="wheel_offset_y" value="0.1675"/>
    <xacro:property name="wheel_radius" value="0.034"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <!-- Base link -->

    <link name="base_link">
    </link>


    <!-- Base footprint link -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>

    <!-- Chassis link -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="-0.1 0 0" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 0.15" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} 0.3 0.3"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="${chassis_length/2} 0 0.15" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} 0.3 0.3"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="1.0" x="${chassis_length}" y="0.3" z="0.3">
            <origin xyz="${chassis_length/2} 0 0.15" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- Left wheel link -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.05" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <!-- Right wheel link -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>
    
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.05" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- CASTER WHEEL -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="0.3 0 0" rpy="0 0 0"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.03" />
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.03" />
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="0.01" radius="0.03">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001" />
        <mu2 value="0.001" />
    </gazebo>


</robot>